=== kikogassen/UFSM/6º Semestre/Linguagens de Marcação Extensíveis/Prova Demo/Mariano/defesadrgio.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2019 rel. 3 sp1 (x64) (http://www.altova.com) by Frederico Hansel dos Santos Gassen (Universidade Federal de Santa Maria) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="apresentacao">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="abertura">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="titulo" type="xs:string"/>
							<xs:element name="subtitulo" type="xs:string"/>
							<xs:element name="autores"/>
							<xs:element name="instituicao" type="xs:string"/>
							<xs:element name="localidade" type="xs:string"/>
							<xs:element name="data" type="xs:string"/>
							<xs:element name="palavras-chave">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="palavra-chave" type="xs:string" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="resumo" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="corpo">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="slide" type="slideType" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="slideType">
		<xs:sequence>
			<xs:element name="cabecalho" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="titulo" type="xs:string"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="corpo">
				<xs:complexType>
					<xs:choice maxOccurs="unbounded">
						<xs:element name="lista">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="item" maxOccurs="unbounded">
										<xs:complexType>
											<xs:choice maxOccurs="unbounded">
												<xs:element name="lista"/>
												<xs:element name="texto" type="xs:string"/>
												<xs:element name="bloco-realce">
													<xs:complexType>
														<xs:choice maxOccurs="unbounded">
															<xs:element name="texto" type="xs:string"/>
															<xs:element name="bloco-realce"/>
														</xs:choice>
														<xs:attribute name="tipo" type="xs:string" use="required"/>
													</xs:complexType>
												</xs:element>
											</xs:choice>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
								<xs:attribute name="tipo" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
						<xs:element name="tabela" type="tabelaType"/>
						<xs:element name="texto" type="xs:string"/>
						<xs:element name="imagem" type="imagemType"/>
						<xs:element name="bloco-realce">
							<xs:complexType>
								<xs:choice maxOccurs="unbounded">
									<xs:element name="texto" type="xs:string"/>
									<xs:element name="bloco-realce"/>
								</xs:choice>
								<xs:attribute name="tipo" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
						<xs:element name="br"/>
					</xs:choice>
				</xs:complexType>
			</xs:element>
			<xs:element name="rodape" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="data" type="xs:string"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="titulo" type="xs:string" use="required"/>
		<xs:attribute name="codigo" type="xs:ID" use="required"/>
	</xs:complexType>
	<xs:complexType name="tabelaType">
		<xs:sequence>
			<xs:element name="linha">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="celula" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="lista" maxOccurs="unbounded">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="item" maxOccurs="unbounded">
													<xs:complexType>
														<xs:choice maxOccurs="unbounded">
															<xs:element name="lista"/>
															<xs:element name="texto" type="xs:string"/>
															<xs:element name="bloco-realce">
																<xs:complexType>
																	<xs:choice maxOccurs="unbounded">
																		<xs:element name="texto" type="xs:string"/>
																		<xs:element name="bloco-realce"/>
																	</xs:choice>
																	<xs:attribute name="tipo" type="xs:string" use="required"/>
																</xs:complexType>
															</xs:element>
														</xs:choice>
													</xs:complexType>
												</xs:element>
											</xs:sequence>
											<xs:attribute name="tipo" type="xs:string" use="required"/>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="borda" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="imagemType">
		<xs:sequence>
			<xs:element name="figura">
				<xs:complexType>
					<xs:attribute name="uri" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="legenda" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== kikogassen/UFSM/6º Semestre/Linguagens de Marcação Extensíveis/Prova Demo/defesadrgio.xml
<?xml version="1.0" encoding="UTF-8"?>
<apresentacao xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/kikog/Documents/UFSM/6%C2%BA%20Semestre/Linguagens%20de%20Marca%C3%A7%C3%A3o%20Extens%C3%ADveis/Prova%20Demo/Mariano/defesadrgio.xsd">
	<abertura>
		<titulo>Topic Maps:</titulo>
		<subtitulo>da sintaxe à semântica</subtitulo>
		<autores>
			<autor>
				<nome>Giovani Rubert Librelotto</nome>
				<email>grl@di.uminho.pt</email>
			</autor>
		</autores>
		<instituicao>Universidade do Minho</instituicao>
		<localidade>Braga - Portugal</localidade>
		<data>Setembro de 2005</data>
		<palavras-chave>
			<palavra-chave>Tese Topic Maps</palavra-chave>
			<palavra-chave>Topic Maps</palavra-chave>
			<palavra-chave>XML</palavra-chave>
			<palavra-chave>ISO 13250</palavra-chave>
			<palavra-chave>Metarmophosis</palavra-chave>
			<palavra-chave>XTche</palavra-chave>
			<palavra-chave>Ulisses</palavra-chave>
			<palavra-chave>Giovani Librelotto</palavra-chave>
			<palavra-chave>Processamento Semântico</palavra-chave>
			<palavra-chave>Ontologias</palavra-chave>
			<palavra-chave>Universidade do Minho</palavra-chave>
		</palavras-chave>
		<resumo>
			Sendo necessário um mecanismo de validação para garantir a preservação da semântica de cada topic map, o que aqui se defende é um sistema (uma linguagem e seu processador) para a especificação de restrições em TM com base num conjunto de regras.
		</resumo>
	</abertura>
	<corpo>
		<slide titulo="Contexto da Tese" codigo="S001">
			<cabecalho>
				<titulo>Topic Maps</titulo>
			</cabecalho>
			<corpo>
				<lista tipo="normal">
					<item>
						<texto>Processamento de documentos estruturados;</texto>
					</item>
					<item>
						<texto>Processamento semântico de documentos;</texto>
					</item>
					<item>
						<texto>XML</texto>
					</item>
					<item>
						<texto>Ontologias</texto>
					</item>
					<item>
						<texto>ISO 13250 Topic Maps</texto>
					</item>
				</lista>
			</corpo>
			<rodape>
				<data>Setembro 2005</data>
			</rodape>
		</slide>
		<slide titulo="Topic Maps: características" codigo="S002">
			<corpo>
				<lista tipo="normal">
					<item>
						<texto>Permitem estabelecer uma rede associativa e estruturada entre os tópicos, permitindo navegação sobre a mesma;</texto>
					</item>
					<item>
						<texto>Organizam hierarquicamente os recursos num novo domínio de informação/conhecimento, relacionando-os com os tópicos;</texto>
					</item>
					<item>
						<texto>Propiciam a interoperabilidade entre recursos de informação distintos, através de uma visão conceptual integrada da ontologia sobre o domínio.</texto>
					</item>
				</lista>
			</corpo>
		</slide>
		<slide titulo="Motivação: o problema" codigo="S003">
			<corpo>
				<tabela borda="0">
					<linha>
						<celula>
							<lista tipo="normal">
								<item>
									<texto>Vantagem de TM: </texto>
									<bloco-realce tipo="negrito">
										<texto>liberdade em sua criação</texto>
									</bloco-realce>
									<lista tipo="normal">
										<item>
											<texto>Essa liberdade pode por em risco a sua consistência;</texto>
										</item>
									</lista>
								</item>
								<item>
									<texto>Validação semântica manual é possível</texto>
									<lista tipo="normal">
										<item>
											<texto>Contudo, para TM de tamanho considerável, é inviável.</texto>
										</item>
									</lista>
								</item>
							</lista>
						</celula>
						<celula>
							<lista tipo="normal">
								<item>
									<texto>A norma TM não possui mecanismos para restrições semânticas em mapas de tópicos</texto>
									<lista tipo="normal">
										<item>
											<texto>Restrições estruturais são definidas pelo DTD de XTM;</texto>
										</item>
										<item>
											<texto>ISO 19756 TMCL está em fase de discussão;</texto>
										</item>
									</lista>
								</item>
							</lista>
						</celula>
					</linha>
				</tabela>
			</corpo>
		</slide>
		<slide titulo="A Tese" codigo="S004">
			<corpo>
				<texto>Sendo necessário um mecanismo de validação para garantir a preservação da semântica de cada topic map, 
	o que aqui se defende é um sistema (uma linguagem e seu processador) para a especificação de restrições em TM com base num conjunto de regras.</texto>
			</corpo>
		</slide>
		<slide titulo="Topic Maps - TAO" codigo="S005">
			<corpo>
				<lista tipo="normal">
					<item>
						<bloco-realce tipo="negrito">
							<texto>T</texto>
						</bloco-realce>
						<texto> refere-se ao tópico:</texto>
						<lista tipo="normal">
							<item>
								<texto>representa um tema dentro do universo de discurso:</texto>
								<lista tipo="normal">
									<item>
										<texto>Ex: Universidade do Minho, comboio, Portugal, artigo, …</texto>
									</item>
								</lista>
							</item>
						</lista>
					</item>
					<item>
						<bloco-realce tipo="negrito">
							<texto>A</texto>
						</bloco-realce>
						<texto> refere-se à associação: </texto>
						<lista tipo="normal">
							<item>
								<texto>é um relacionamento entre um ou mais tópicos, onde cada tópico desempenha um papel de actuação:</texto>
								<lista tipo="normal">
									<item>
										<texto>Ex: escrever, importar, fazer, empregar, …</texto>
									</item>
								</lista>
							</item>
						</lista>
					</item>
					<item>
						<bloco-realce tipo="negrito">
							<texto>O</texto>
						</bloco-realce>
						<texto> refere-se à ocorrência:  </texto>
						<lista tipo="normal">
							<item>
								<texto>ligação aos recursos de informação relevante para um dado tópico:</texto>
								<lista tipo="normal">
									<item>
										<texto>Ex: http://www.uminho.pt, mailto:librelotto@gmail.com, …</texto>
									</item>
								</lista>
							</item>
						</lista>
					</item>
				</lista>
			</corpo>
		</slide>
		<slide titulo="Ontologia expressa em Topic Maps" codigo="S006">
			<corpo>
				<imagem>
					<figura uri="imagens/ontologiaexpressaemtopicmaps.gif"/>
					<legenda>Ilustração ontologia expressa em topic maps</legenda>
				</imagem>
			</corpo>
		</slide>
		<slide titulo="Linguagens de Representação de TM" codigo="S007">
			<corpo>
				<bloco-realce tipo="negrito">
					<bloco-realce tipo="sublinhado">
						<texto>Gerais:</texto>
					</bloco-realce>
				</bloco-realce>
				<br/>
				<lista tipo="normal">
					<item>
						<texto>AsTMa=</texto>
						<lista tipo="normal">
							<item>
								<texto>sintaxe baseada na linguagem AsTMa;</texto>
							</item>
						</lista>
					</item>
					<item>
						<texto>LTM</texto>
						<lista tipo="normal">
							<item>
								<texto>representa os construtores de TM como texto em um formato simplificado e compacto.</texto>
							</item>
						</lista>
					</item>
				</lista>
				<bloco-realce tipo="negrito">
					<bloco-realce tipo="sublinhado">
						<texto>Baseadas em XML:</texto>
					</bloco-realce>
				</bloco-realce>
				<br/>
				<lista tipo="normal">
					<item>
						<texto>HyTM</texto>
						<lista tipo="normal">
							<item>
								<texto>dialecto SGML baseado em HyTime;</texto>
							</item>
						</lista>
					</item>
					<item>
						<texto>XTM</texto>
						<lista tipo="normal">
							<item>
								<texto>documento XML onde diferentes elementos são usados para representar tópicos, ocorrências, associações, etc;</texto>
							</item>
						</lista>
					</item>
				</lista>
			</corpo>
		</slide>
		<slide titulo="Metamorphosis: objectivo" codigo="S008">
			<corpo>
				<imagem>
					<figura uri="imagens/metamosphosis_objetivo.gif"/>
					<legenda>Ilustração do Objetivo de Metamorphosis</legenda>
				</imagem>
			</corpo>
		</slide>
		<slide titulo="Metamorphosis: Arquitectura" codigo="S009">
			<corpo>
				<imagem>
					<figura uri="imagens/metamosphosis_arquitetura.gif"/>
					<legenda>Ilustração da Arquitetura de Metamorphosis</legenda>
				</imagem>
			</corpo>
		</slide>
		<slide titulo="Oveia" codigo="S010">
			<corpo>
				<imagem>
					<figura uri="imagens/oveia.gif"/>
					<legenda>Ilustração do funcionamento de Oveia</legenda>
				</imagem>
			</corpo>
		</slide>
		<slide titulo="XTche" codigo="S011">
			<corpo>
				<imagem>
					<figura uri="imagens/xtche.gif"/>
					<legenda>Ilustração do uso de XTche</legenda>
				</imagem>
			</corpo>
		</slide>
		<slide titulo="Ulisses" codigo="S012">
			<corpo>
				<imagem>
					<figura uri="imagens/ulisses.gif"/>
					<legenda>Ilustração do uso de Ulisses</legenda>
				</imagem>
			</corpo>
		</slide>
		<slide titulo="Restrições em XTche: objectivos" codigo="S013">
			<corpo>
				<lista tipo="normal">
					<item>
						<texto>Verificar se a estrutura de um TM está de acordo com um conjunto de regras semânticas;</texto>
					</item>
					<item>
						<texto>Gerar relatórios sobre um TM concreto;</texto>
					</item>
					<item>
						<texto>Permitir a especificação de esquemas para TM de uma mesma família:</texto>
						<lista tipo="normal">
							<item>
								<texto>Esquemas: regras a serem obedecidas pelos TM de uma família;</texto>
							</item>
						</lista>
					</item>
				</lista>
			</corpo>
		</slide>
		<slide titulo="Implementação desejada de XTche" codigo="S014">
			<corpo>
				<lista tipo="normal">
					<item>
						<texto>Seguir a norma ISO 19756: TMCL</texto>
					</item>
					<item>
						<texto>Tornar a validação simples;</texto>
					</item>
					<item>
						<texto>Fazer isso utilizando uma tecnologia existente;</texto>
					</item>
					<item>
						<texto>Tornar user-friendly</texto>
						<lista tipo="normal">
							<item>
								<texto>Se possível, não obrigar o utilizador a ter que aprender uma nova linguagem.</texto>
							</item>
						</lista>
					</item>
				</lista>
			</corpo>
		</slide>
		<slide titulo="Linguagem XTche" codigo="S015">
			<corpo>
				<lista tipo="normal">
					<item>
