=== kikogassen/UFSM/6º Semestre/Linguagens de Marcação Extensíveis/agenda.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ELEMENT agenda (entrada|grupo)*>

<!ELEMENT grupo (entrada|ref)*>
<!ATTLIST grupo gid ID #REQUIRED>

<!ELEMENT entrada (nome, email?, telefone)>
<!ATTLIST entrada id ID #REQUIRED>
<!ATTLIST entrada tipo CDATA #IMPLIED>

<!ELEMENT ref EMPTY>
<!ATTLIST ref entref IDREF #REQUIRED>

<!ELEMENT nome (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT telefone (#PCDATA)>

=== kikogassen/UFSM/6º Semestre/Linguagens de Marcação Extensíveis/agenda.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE agenda SYSTEM "agenda.dtd">
<agenda>
	<entrada id="e1" tipo="pessoa">
		<nome>Giovani Rubert Librelotto</nome>
		<!--email>librelotto@inf.ufsm.br</email-->
		<telefone>555-1234</telefone>
	</entrada>
	<grupo gid="ufsm">
		<entrada id="e2" tipo="pessoa">
			<nome>Eduardo Piveta</nome>
			<email>piveta@inf.ufsm.br</email>
			<telefone>555-1235</telefone>
		</entrada>
		<entrada id="e3" tipo="pessoa">
			<nome>Juliana Vizzotto</nome>
			<email>juvizzotto@inf.ufsm.br</email>
			<telefone>555-1236</telefone>
		</entrada>
		<ref entref="e1"/>
		<ref entref="e5"/>
	</grupo>
	<entrada id="e4" tipo="empresa">
		<nome>Lavandaria Tudo Branco</nome>
		<telefone>555-1212</telefone>
	</entrada>
	<entrada id="e5" tipo="pessoa">
		<nome>José Alves de Castro</nome>
		<telefone>555-1231</telefone>
	</entrada>
	<entrada id="e6" tipo="pessoa">
		<nome>Giordano Librelotto</nome>
		<telefone>555-1313</telefone>
	</entrada>
	<grupo gid="familia">
		<entrada id="e7">
			<nome>Diógenes Librelotto</nome>
			<telefone>555-1414</telefone>
		</entrada>
		<ref entref="e1"/>
		<ref entref="e6"/>
		<entrada id="e8">
			<nome>Bianca Librelotto</nome>
			<telefone>555-1515</telefone>
		</entrada>
	</grupo>
</agenda>
