=== kikogassen/UFSM/6º Semestre/Linguagens de Marcação Extensíveis/DocumentComposer/composer.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 3 U (http://www.xmlspy.com) by rth77 (rth77) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:element name="new-doc">
    <xs:annotation>
      <xs:documentation>Comment describing your root element</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element name="target" type="xs:string"/>
        <xs:element name="part" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="source" type="xs:string"/>
              <xs:element name="container" type="xs:string" minOccurs="0"/>
              <xs:element name="query-set">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="query" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="container" type="xs:string" minOccurs="0"/>
                          <xs:element name="qexp" type="xs:string"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== kikogassen/UFSM/6º Semestre/Linguagens de Marcação Extensíveis/DocumentComposer/XPQL_EVO.xml
<?xml version="1.0" encoding="UTF-8"?>
<new-doc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="composer.xsd">
	<target>doc-result</target>
	<part>
		<source>arq-son-EVO.xml</source>
		<container>result-set</container>
		<query-set>	
			<query>
				<container>result</container>
				<qexp>//tit[contains(.,'Jesus')]</qexp>
			</query>
			<query>
				<container>result</container>
				<qexp>//musico</qexp>
			</query>
			<query>
				<container>result</container>
				<qexp>//doc/tit[contains(../local,'Castelo Branco')]</qexp>
			</query>
		</query-set>			
	</part>
</new-doc>

=== kikogassen/UFSM/6º Semestre/Linguagens de Marcação Extensíveis/DocumentComposer/XPQL_exercicio.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<new-doc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="composer.xsd">
	<target>resultado</target>
	<part>
		<source>agenda.xml</source>
		<container>Entrada555</container>
		<query-set>
			<query>
				<qexp>//entrada[starts-with(telefone,'555')]</qexp>
			</query>
		</query-set>
	</part>
	<part>
		<source>poema.xml</source>
		<container>VersoNãoTemNome</container>
		<query-set>
			<query>
				<qexp>//verso[not(nome)]</qexp>
			</query>
		</query-set>
	</part>
</new-doc>

=== kikogassen/UFSM/6º Semestre/Linguagens de Marcação Extensíveis/XPQL_poema.xml
<?xml version="1.0" encoding="UTF-8"?>
<new-doc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="composer.xsd">
	<target>poema_result</target>
	<part>
		<source>poema.xml</source>
		<container>quadra4_verso3</container>
		<query-set>
			<query>
				<qexp>quadra[last()]/verso[3]</qexp>
			</query>
		</query-set>
	</part>
	<part>
		<source>poema.xml</source>
		<container>nomes</container>
		<query-set>
			<query>
				<qexp>//nome</qexp>
			</query>
		</query-set>
	</part>
	<part>
		<source>poema.xml</source>
		<container>terno2</container>
		<query-set>
			<query>
				<qexp>terno[2]/verso</qexp>
			</query>
		</query-set>
	</part>
	<part>
		<source>poema.xml</source>
		<container>nomes_lugares_L</container>
		<query-set>
			<query>
				<qexp>nome[starts-with(.,'L')] | lugar[starts-with(.,'L')]</qexp>
			</query>
		</query-set>
	</part>
</new-doc>

=== kikogassen/UFSM/6º Semestre/Linguagens de Marcação Extensíveis/DocumentComposer/XPQL_agenda.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<new-doc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="composer.xsd">
	<target>agenda_result</target>
	<part>
		<source>agenda.xml</source>
		<container>entrada_fone_253</container>
		<query-set>
			<query>
				<qexp>//entrada[starts-with(telefone,'555')]</qexp>
			</query>
		</query-set>
	</part>
	<part>
		<source>agenda.xml</source>
		<container>mail_unifra</container>
		<query-set>
			<query>
				<qexp>//entrada[contains(email,'unifra.br')]</qexp>
			</query>
		</query-set>
	</part>
	<part>
		<source>agenda.xml</source>
		<container>entrada_referencias</container>
		<query-set>
			<query>
				<qexp>//entrada[@id = //ref/@entref]/nome</qexp>
			</query>
		</query-set>
	</part>
</new-doc>

=== kikogassen/UFSM/6º Semestre/Linguagens de Marcação Extensíveis/XPQL_jcrpubs.xml
<?xml version="1.0" encoding="UTF-8"?>
<new-doc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="composer.xsd">
	<target>bienio0304</target>
	<part>	
		<source>jcrpubs.xml</source>
		<container>pubs2003</container>
		<query-set>
			<query>
				<qexp>//*[year='2003']</qexp>
			</query>
		</query-set>
	</part>
	<part>
		<source>jcrpubs.xml</source>
		<container>authors</container>
		<query-set>
			<query>
				<qexp>//author</qexp>
			</query>
		</query-set>
	</part>
</new-doc>

=== kikogassen/UFSM/6º Semestre/Linguagens de Marcação Extensíveis/DocumentComposer/XPQL_GioMovies.xml
<?xml version="1.0" encoding="UTF-8"?>
<new-doc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="composer.xsd">
	<target>GioMovies</target>
	<part>
		<source>GioMovies.xml</source>
		<container>Filmes1998</container>
		<query-set>
			<query>
				<qexp>//filme[ano='1998']</qexp>
			</query>
		</query-set>
	</part>
	<part>
		<source>GioMovies.xml</source>
		<container>Duracao120-140</container>
		<query-set>
			<query>
				<qexp>//filme[duracao&gt;119 and duracao&lt;141]/tituloBR</qexp>
			</query>
		</query-set>
	</part>
</new-doc>

=== kikogassen/UFSM/6º Semestre/Linguagens de Marcação Extensíveis/XPQL_poema_agenda.xml
<?xml version="1.0" encoding="UTF-8"?>
<new-doc xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="composer.xsd">
	<target>main</target>
	<part>
		<source>poema.xml</source>
		<container>poema</container>
		<query-set>
			<query>
				<container>q1</container>
				<qexp>quadra[1]/verso[2]</qexp>
			</query>
		</query-set>
	</part>
	<part>
		<source>agenda.xml</source>
		<container>agenda</container>
		<query-set>
			<query>
				<qexp>//entrada[@tipo='empresa']</qexp>
			</query>
		</query-set>
	</part>
	<part>
		<source>poema.xml</source>
		<query-set>
			<query>
				<container>nomes</container>
				<qexp>//nome</qexp>
			</query>
		</query-set>
	</part>
	<part>
		<source>agenda.xml</source>
		<query-set>
			<query>
				<container>nomes</container>
				<qexp>//nome</qexp>
			</query>
		</query-set>
	</part>	
</new-doc>
